spring:
  datasource:
    url: 'jdbc:h2:mem:${database_schema};DB_CLOSE_DELAY=-1'
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
logging:
  level:
    org:
      flywaydb: INFO
